version: '3.8'

services:
  postgres_database:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: secret_2
      POSTGRES_DB: db
      POSTGRES_USER: practica3_user
    networks:
      - Practica3-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s
    user: practica3_user 

  api:
    image: dinver20/api-practica3:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_PASSWORD: secret_2
      DATABASE_NAME: db
      DATABASE_HOST: postgres_database
      DATABASE_USERNAME: practica3_user
    networks:
      - Practica3-network

networks:
  Practica3-network:
    driver: overlay

volumes:
  postgres-data:
    driver: local