version: '3.8'

services:
  postgres_database:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: secret_2
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    networks:
      - Practica3-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s
    user: postgres

  api:
    image: dinver20/api-practica3:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_PASSWORD: secret_2
      DATABASE_NAME: db
      DATABASE_HOST: postgres_database
      DATABASE_USERNAME: postgres
    networks:
      - Practica3-network

networks:
  Practica3-network:
    driver: overlay

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfs01,rw"
      device: ":/data/docker-vols/grupo6/postgres_data"