version: '3.9'

services:

  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
    env_file: ".env"
    networks:
      - Practica3-network
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - Practica3-network

networks:
  Practica3-network:
    driver: bridge
  